services:
  db:
    image: mysql
    container_name: lockify-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lockifydb
    ports:
      - "3333:3306"
  api:
    build: .
    container_name: lockify-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - .env
    command: ["nodemon", "-L", "--watch", "src", "src/main.js"]